config/routes.rb
Rails.application.routes.draw do
  # Api Section
  namespace :api do
    resources :teams
    resources :matches
  end

  get '/howitworks', to: 'hiw#index'
  resources :teams
  resources :matches
  devise_for :users, :path => 'accounts'
  resources :users do
    resources :bets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'matches#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :match
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :local_team, :class_name => 'Team'
  belongs_to :visitor_team, :class_name => 'Team'
  has_many :bets
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :matches
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bets
end

app/controllers/api/matches_controller.rb
class Api::MatchesController < MatchesController
  before_action :set_default_format

  private

    def set_default_format
      request.format = :json
    end
end

app/controllers/api/teams_controller.rb
class Api::TeamsController < TeamsController
  before_action :set_default_format

  private

    def set_default_format
      request.format = :json
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def show
  end

  def new
    @bet = Bet.new
    @match = Match.find(params[:match_id].to_i)
  end

  def create
  end
end

app/controllers/hiw_controller.rb
class HiwController < ApplicationController
  def index
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :find_match, only: [:show, :edit, :update, :destroy]

  def index
    @matches = Match.all.order('kickoff')
  end

  def show
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to @match, notice: 'Match Added!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @match.update(match_params)
      redirect_to @match, notice: 'Match was updated'
    else
      render 'edit'
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_path
  end

  def update_total_purse
    @match.total_purse = @match.local_purse + @match.tie_purse + @match.visitor_purse
  end

  private

    def match_params
      params.require(:match).permit(:kickoff, :local_purse, :tie_purse, :visitor_purse, :total_purse, :local_team_id, :visitor_team_id)
    end

    def find_match
      @match = Match.find(params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all.order('created_at')
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/hiw_helper.rb
module HiwHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/bets/new.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-body
        .row
          .col-md-2
            %img{ src: @match.local_team.image_url, class: 'small-image' }
          .col-md-8.vertical-center
            %h4
              = @match.local_team.name
          .col-md-2
            = link_to number_with_precision(@match.total_purse / @match.local_purse,
            precision: 2), root_path, class: 'btn btn-warning'
        .row
          .col-md-8.col-md-offset-2.vertical-center
            %h4 x
          .col-md-2
            = link_to number_with_precision(@match.total_purse / @match.tie_purse,
            precision: 2), root_path, class: 'btn btn-warning'
        .row
          .col-md-2
            %img{ src: @match.visitor_team.image_url, class: 'small-image' }
          .col-md-8.vertical-center
            %h4
              = @match.visitor_team.name
          .col-md-2
            = link_to number_with_precision(@match.total_purse / @match.visitor_purse,
            precision: 2), root_path, class: 'btn btn-warning'
        %p
          Kickoff
          = @match.kickoff
      .panel-footer
        .row
          .col-md-5
            .btn-group{"data-toggle" => "buttons"}
              %label.btn.btn-primary
                %input{:autocomplete => "off", :type => "checkbox"}/
                Local
              %label.btn.btn-primary
                %input{:autocomplete => "off", :type => "checkbox"}/
                Tie
              %label.btn.btn-primary
                %input{:autocomplete => "off", :type => "checkbox"}/
                Visitor
          .col-md-2
            %h4 Amount:
          .col-md-3
            %input.form-control{:placeholder => "$", :type => "text"}/
          .col-md-2
            = link_to 'Echale', root_path, class: 'btn btn-danger pull-right'

app/views/bets/show.html.haml
%h1 hello bets

app/views/hiw/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>How betting works</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <h2>What the odds mean</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <h2>Example</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Echale</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <strong><%= link_to "Echale", root_path, class: 'navbar-brand' %></strong>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "How it Works", howitworks_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default' %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path, class: 'btn btn-info' %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/matches/_form.html.haml
= simple_form_for @match, html: { multipart: true } do |f|
  - if @match.errors.any?
    #errors
      %h2
      = pluralize(@match.errors.count, "error")
      prevented this Match from saving
      %ul
        - @match.errors.full_messages.each do |msg|
          %li
            = msg

  .form-group
    = f.select :local_team_id, Team.all.collect {|c| [ c.name, c.id ] }, include_blank: true
  .form-group
    = f.select :visitor_team_id, Team.all.collect {|c| [ c.name, c.id ] }, include_blank: true

  .form-group
    = f.input :kickoff, input_html: { class: 'form-control'}

  = f.button :submit, class: 'btn btn-info'

app/views/matches/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Match
      .panel-body
        .current_image
          = render 'form'
          = link_to 'Cancel', team_path

app/views/matches/index.html.haml
.row
  .col-md-6.col-md-offset-3
    #matches.transitions-enabled
      - @matches.each do |match|
        .panel.panel-default
          .panel-body
            .row
              .col-md-2
                %img{ src: match.local_team.image_url, class: 'small-image' }
              .col-md-8.vertical-center
                %h4
                  = match.local_team.name
              .col-md-2
                = number_with_precision(match.total_purse / match.local_purse,
                precision: 2)
            .row
              .col-md-8.col-md-offset-2.vertical-center
                %p x
              .col-md-2
                = number_with_precision(match.total_purse / match.tie_purse,
                precision: 2)
            .row
              .col-md-2
                %img{ src: match.visitor_team.image_url, class: 'small-image' }
              .col-md-8.vertical-center
                %h4
                  = match.visitor_team.name
              .col-md-2
                = number_with_precision(match.total_purse / match.visitor_purse,
                precision: 2)
          .panel-footer
            - if user_signed_in?
              = link_to 'Echale', new_user_bet_path(user_id: current_user.id, match_id: match.id), class: 'btn btn-danger pull-right'
            - else
              = link_to 'Echale', new_user_session_path, class: 'btn btn-danger pull-right'
            %p
              Total Purse: $
              = match.total_purse
              , Kickoff:
              = match.kickoff

app/views/matches/new.html.haml
%h1 Post Match
= render 'form'
= link_to 'Back', matches_path

app/views/matches/show.html.haml
%p= link_to 'Back to Matches', matches_path
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-header
        %h4
          Kickoff
          = @match.kickoff
      .panel-body
        .pull-right
          = link_to number_with_precision(@match.total_purse / @match.local_purse,
          precision: 2), edit_match_path, class: 'btn btn-warning'
        %h2= @match.local_team.name
        .pull-right
          = link_to number_with_precision(@match.total_purse / @match.tie_purse,
          precision: 2), edit_match_path, class: 'btn btn-warning'
        %h2 Empate
        .pull-right
          = link_to number_with_precision(@match.total_purse / @match.visitor_purse,
          precision: 2), edit_match_path, class: 'btn btn-warning'
        %h2= @match.visitor_team.name

      .panel-footer
        .row
          .col-md-6
            %h4
              Amount
          .col-md-6
            .pull-right
              %h4
                Total Purse
                = @match.total_purse